{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
apiVersion: zalando.org/v1
kind: AWSIAMRole
metadata:
  name: emergency-access-service-aws-iam-credentials
  namespace: kube-system
spec:
  roleReference: {{.LocalID}}-emergency-access-service
{{ end }}
