{{ $version := "v0.0.3" }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-ready
  namespace: kube-system
  labels:
    application: kube-node-ready
    version: {{$version}}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: kube-node-ready
  template:
    metadata:
      labels:
        application: kube-node-ready
        version: {{$version}}
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "false"}}
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-kube-node-ready"
{{ end }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: kube-node-ready
        image: registry.opensource.zalan.do/teapot/kube-node-ready:{{$version}}
        args:
        - --lifecycle-hook=kube-node-ready-lifecycle-hook
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
        env:
        # must be set for the AWS SDK/AWS CLI to find the credentials file.
        - name: AWS_SHARED_CREDENTIALS_FILE # used by golang SDK
          value: /meta/aws-iam/credentials.process
{{ end }}
        resources:
          limits:
            cpu: 1m
            memory: 50Mi
          requests:
            cpu: 1m
            memory: 50Mi
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
        volumeMounts:
        - name: aws-iam-credentials
          mountPath: /meta/aws-iam
          readOnly: true
{{ end }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 300
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
{{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "true"}}
      volumes:
      - name: aws-iam-credentials
        secret:
          secretName: kube-node-ready-aws-iam-credentials
{{ end }}
